name: Sync Leetcode Past History
on:
  workflow_dispatch: # Allows manual click
  schedule:
    - cron: "0 0 * * *" # Automatically runs every night at midnight UTC
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Sync Script
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: leetcode-problems
